- name: my_first_playbook
  hosts: web_servers
  gather_facts: false
  tasks:

    - name: Stop gather_facts and update cache
      apt:
        update_cache: true

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Copy index.html
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: Restart nginx
      sysvinit:
        name: nginx
        state: restarted

